# Generated by Django 2.2.3 on 2019-09-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.FloatField(default=23.7),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.FloatField(default=90.4),
        ),
    ]
