# Generated by Django 2.2.3 on 2019-09-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190901_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PND', 'Pending'), ('OTW', 'OnTheWay'), ('DLV', 'Delivered')], default='PND', max_length=3),
        ),
    ]
